# Generated by Django 4.2.9 on 2025-02-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_parseddata_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Uploaded a PDF'), ('PARSE', 'Parsed social media data'), ('CLASSIFY', 'Classified message'), ('DELETE', 'Deleted a history entry')], max_length=50),
        ),
    ]
